wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: glorot_uniform
