wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: glorot_uniform
