wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: glorot_uniform
