wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: glorot_uniform
