wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random_normal
