wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: glorot_uniform
