wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 32
epochs:
  value: 15
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
