wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 15
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
